pragma solidity >=0.4.24;


import "../../node_modules/openzeppelin-solidity/contracts/ownership/Ownable.sol";

// Import the library 'Roles'
import "../access-control/FarmerRole.sol";
import "../access-control/DistributorRole.sol";
import "../access-control/RetailerRole.sol";
import "../access-control/ConsumerRole.sol";


// Define a contract 'Supplychain'
contract SupplyChain is Ownable, FarmerRole, DistributorRole, RetailerRole, ConsumerRole {


  // Define 'owner'
  // address payable owner;

  // Define a variable called 'upc' for Universal Product Code (UPC)
  uint  upc;

  // Define a variable called 'sku' for Stock Keeping Unit (SKU)
  uint  sku;

    // Define enum 'State' with the following values:
    enum State
    {
        Harvested,  // 0
        Processed,  // 1
        Packed,     // 2
        ForSale,    // 3
        Sold,       // 4
        Shipped,    // 5
        Received,   // 6
        Purchased   // 7
    }

    struct Item {
        uint    sku;  // Stock Keeping Unit (SKU)
        uint    upc; // Universal Product Code (UPC), generated by the Farmer, goes on the package, can be verified by the Consumer
        address ownerID;  // Metamask-Ethereum address of the current owner as the product moves through 8 stages
        address originFarmerID; // Metamask-Ethereum address of the Farmer
        string  originFarmName; // Farmer Name
        string  originFarmInformation;  // Farmer Information
        string  originFarmLatitude; // Farm Latitude
        string  originFarmLongitude;  // Farm Longitude
        uint    productID;  // Product ID potentially a combination of upc + sku
        string  productNotes; // Product Notes
        uint    productPrice; // Product Price
        State   itemState;  // Product State as represented in the enum above
        address distributorID;  // Metamask-Ethereum address of the Distributor
        address retailerID; // Metamask-Ethereum address of the Retailer
        address payable consumerID; // Metamask-Ethereum address of the Consumer
    }

  // Define a public mapping 'items' that maps the UPC to an Item.
  mapping (uint => Item) items;

  State constant defaultState = State.Harvested;

  // Define a public mapping 'itemsHistory' that maps the UPC to an array of TxHash,
  // that track its journey through the supply chain -- to be sent from DApp.
  //mapping (uint => bytes32[]) txItemsHistory;
  //mapping (bytes32 => Item) itemsHistory;

  // Define a struct 'Item' with the following fields:
  // Define 8 events with the same 8 state values and accept 'upc' as input argument
  event Harvested(uint upc);
  event Processed(uint upc);
  event Packed(uint upc);
  event ForSale(uint upc);
  event Sold(uint upc);
  event Shipped(uint upc);
  event Received(uint upc);
  event Purchased(uint upc);

  // Define a modifer that verifies the Caller
  modifier verifyCaller(address _address) {
    require(msg.sender == _address, "Are you joking?");
    _;
  }

  // Define a modifier that checks if the paid amount is sufficient to cover the price
  modifier paidEnough(uint _price) {
    require(msg.value >= _price, "I can not accept less than it worth");
    _;
  }

  // Define a modifier that checks the price and refunds the remaining balance
  modifier checkValue(uint _upc) {
    _;
    uint _price = items[_upc].productPrice;
    uint amountToReturn = msg.value - _price;
    items[_upc].consumerID.transfer(amountToReturn);
  }

  // Define a modifier that checks if an item.state of a upc is Harvested
  modifier harvested(uint _upc) {
    require(items[_upc].itemState == State.Harvested, "Not in harvest");
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Processed
  modifier processed(uint _upc) {
    require(items[_upc].itemState == State.Processed, "Not in process");
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Packed
  modifier packed(uint _upc) {
    require(items[_upc].itemState == State.Packed, "Not in package");
    _;
  }

  // Define a modifier that checks if an item.state of a upc is ForSale
  modifier forSale(uint _upc) {
    require(items[_upc].itemState == State.ForSale, "Not for sale");
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Sold
  modifier sold(uint _upc) {
    require(items[_upc].itemState == State.Sold, "Not sold yet");
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Shipped
  modifier shipped(uint _upc) {
    require(items[_upc].itemState == State.Shipped, "Not shipped yet");
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Received
  modifier received(uint _upc) {
    require(items[_upc].itemState == State.Received, "Still not received");
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Purchased
  modifier purchased(uint _upc) {
    require(items[_upc].itemState == State.Purchased, "Not purchased");
    _;
  }

  // In the constructor set 'owner' to the address that instantiated the contract
  // and set 'sku' to 1
  // and set 'upc' to 1
  constructor() public payable {
    //owner = msg.sender;
    sku = 1;
    upc = 1;
  }

  // Define a function 'kill' if required
  function kill() public onlyOwner(){
      selfdestruct(msg.sender);
  }

  //function addHistory(Item memory item) private {
  //  bytes32 txHash = sha256(abi.encode(item.sku, item.upc));
  //  txItemsHistory[item.upc].push(txHash);
  //  itemsHistory[txHash] = item;
  //}

  // Define a function 'harvestItem' that allows a farmer to mark an item 'Harvested'
  function harvestItem(uint _upc,
    address _originFarmerID,
    string memory _originFarmName,
    string memory _originFarmInformation,
    string memory _originFarmLatitude,
    string memory _originFarmLongitude,
    string memory _productNotes) public
    verifyCaller(_originFarmerID)
    onlyFarmer()
  {
    //require(farmerRole.isFarmer(_originFarmerID), "You are not a Farmer");

    // Increment sku
    sku = sku + 1;
    //string productID = _upc + "_" + sku;

    Item memory item;

    item.sku = sku;   // Stock Keeping Unit (SKU)
    item.upc = _upc; // Universal Product Code (UPC); generated by the Farmer; goes on the package; can be verified by the Consumer
    item.originFarmName = _originFarmName; // Farmer Name
    item.originFarmInformation = _originFarmInformation;  // Farmer Information
    item.originFarmLatitude = _originFarmLatitude; // Farm Latitude
    item.originFarmLongitude = _originFarmLongitude;  // Farm Longitude
    item.productNotes = _productNotes; // Product Notes
    item.ownerID = _originFarmerID;
    item.originFarmerID = _originFarmerID; // Metamask-Ethereum address of the Farmer
    //item.productID = sha256(sku, _upc);  // Product ID potentially a combination of upc + sku
    item.itemState = defaultState;  // Product State as represented in the enum above

    items[_upc] = item;
    // productPrice; // Product Price
    //distributorID;  // Metamask-Ethereum of the Distributor
    //retailerID; // Metamask-Ether address of the Retailer
    //consumerID; //address of the Consumer

    // Emit the appropriate event
    emit Harvested(_upc);
  }

  // Define a function 'processtItem' that allows a farmer to mark an item 'Processed'
  function processItem(uint _upc) public
    // Call modifier to check if upc has passed previous supply chain stage
    harvested(_upc)
    // Call modifier to verify caller of this function
    verifyCaller(items[_upc].originFarmerID)
  {
    // Update the appropriate fields
    items[_upc].itemState = State.Processed;

    //addHistory(items[_upc]);
    // Emit the appropriate event
    emit Processed(_upc);
  }

  // Define a function 'packItem' that allows a farmer to mark an item 'Packed'
  function packItem(uint _upc) public
    // Call modifier to check if upc has passed previous supply chain stage
    processed(_upc)
    // Call modifier to verify caller of this function
    verifyCaller(items[_upc].originFarmerID)
  {
    // Update the appropriate fields
    items[_upc].itemState = State.Packed;

    //addHistory(items[_upc]);
    // Emit the appropriate event
    emit Packed(_upc);
  }

  // Define a function 'sellItem' that allows a farmer to mark an item 'ForSale'
  function sellItem(uint _upc, uint _price) public
    // Call modifier to check if upc has passed previous supply chain stage
    packed(_upc)
    // Call modifier to verify caller of this function
    verifyCaller(items[_upc].originFarmerID)
  {
    // Update the appropriate fields
    items[_upc].itemState = State.ForSale;
    items[_upc].productPrice = _price;

    //addHistory(items[_upc]);
    // Emit the appropriate event
    emit ForSale(_upc);
  }

  // Define a function 'buyItem' that allows the disributor to mark an item 'Sold'
  // Use the above defined modifiers to check if the item is available for sale, if the buyer has paid enough,
  // and any excess ether sent is refunded back to the buyer
  function buyItem(uint _upc) public payable
    // Call modifier to check if upc has passed previous supply chain stage
    forSale(_upc)
    // Call modifer to check if buyer has paid enough
    paidEnough(items[_upc].productPrice)
    // Call modifer to send any excess ether back to buyer
    checkValue(_upc)
  {
    //Valim: Valida se o remetente é um Distribuidor
    //require(distributorRole.isDistributor(msg.sender), "You are not a Distributor");

    // Update the appropriate fields
    items[_upc].itemState = State.Sold;
    items[_upc].distributorID = msg.sender;

    //addHistory(items[_upc]);
    // Emit the appropriate event
    emit Sold(_upc);
  }

  // Define a function 'shipItem' that allows the distributor to mark an item 'Shipped'
  // Use the above modifers to check if the item is sold
  function shipItem(uint _upc) public
    // Call modifier to check if upc has passed previous supply chain stage
    sold(_upc)
    // Call modifier to verify caller of this function
    verifyCaller(items[_upc].distributorID)
  {
    // Update the appropriate fields
    items[_upc].itemState = State.Shipped;

    //addHistory(items[_upc]);
    // Emit the appropriate event
    emit Shipped(_upc);
  }

  // Define a function 'receiveItem' that allows the retailer to mark an item 'Received'
  // Use the above modifiers to check if the item is shipped
  function receiveItem(uint _upc) public
    // Call modifier to check if upc has passed previous supply chain stage
    shipped(_upc)
    // Access Control List enforced by calling Smart Contract / DApp
  {
    //Valim: Valida se o remetente é um Distribuidor
    //retailerRole.isRetailer(msg.sender);

    // Update the appropriate fields
    items[_upc].itemState = State.Received;
    items[_upc].retailerID = msg.sender;

    //addHistory(items[_upc]);
    // Emit the appropriate event
    emit Received(_upc);
  }

  // Define a function 'purchaseItem' that allows the consumer to mark an item 'Purchased'
  // Use the above modifiers to check if the item is received
  function purchaseItem(uint _upc) public
    // Call modifier to check if upc has passed previous supply chain stage
    received(_upc)
    // Access Control List enforced by calling Smart Contract / DApp
  {
    //Valim: Valida se o remetente é um Distribuidor
    //consumerRole.isConsumer(msg.sender);

    // Update the appropriate fields
    items[_upc].itemState = State.Purchased;
    items[_upc].consumerID = msg.sender;

    //addHistory(items[_upc]);
    // Emit the appropriate eventpera
    emit Purchased(_upc);
  }

  // Define a function 'fetchItemBufferOne' that fetches the data
  function fetchItemBufferOne(uint _upc) public view returns
    (
      uint          itemSKU,
      uint          itemUPC,
      address       ownerID,
      address       originFarmerID,
      string memory originFarmName,
      string memory originFarmInformation,
      string memory originFarmLatitude,
      string memory originFarmLongitude
    )
  {
  // Assign values to the 8 parameters

    itemSKU = items[_upc].sku;
    itemUPC = items[_upc].upc;
    ownerID = items[_upc].ownerID;
    originFarmerID = items[_upc].originFarmerID;
    originFarmName = items[_upc].originFarmName;
    originFarmInformation = items[_upc].originFarmInformation;
    originFarmLatitude = items[_upc].originFarmLatitude;
    originFarmLongitude = items[_upc].originFarmLongitude;

  }

  // Define a function 'fetchItemBufferTwo' that fetches the data
  function fetchItemBufferTwo(uint _upc) public view returns
    (
      uint          itemSKU,
      uint          itemUPC,
      uint          productID,
      string memory productNotes,
      uint          productPrice,
      uint          itemState,
      address       distributorID,
      address       retailerID,
      address       consumerID
    )
  {
    // Assign values to the 9 parameters

    itemSKU = items[_upc].sku;
    itemUPC = items[_upc].sku;
    productID = items[_upc].productID;
    productNotes = items[_upc].productNotes;
    productPrice = items[_upc].productPrice;
    itemState = uint(items[_upc].itemState);
    distributorID = items[_upc].distributorID;
    retailerID = items[_upc].retailerID;
    consumerID = items[_upc].consumerID;

  }
}
